#include "AddOperatorNode.h"
#include "ConstDeclarationNode.h"
#include "DeclarationSequenceNode.h"
#include "ExpressionNode.h"
#include "ImportNode.h"
#include "ModuleNode.h"
#include "Node.h"
#include "ProcedureCallNode.h"
#include "ProcedureDeclarationNode.h"
#include "RelationNode.h"
#include "SimpleExprNode.h"
#include "TypeDeclarationNode.h"
#include "VarDeclarationNode.h"
// TODO remove again; Instead move all those includes into sensible files
