#include "ModuleNode.h"
#include "Node.h"
#include "ProcedureCallNode.h"
#include "ProcedureDeclarationNode.h"
#include "RepeatStatementNode.h"
#include "ReturnStatementNode.h"
#include "SimpleExprNode.h"
#include "StatementNode.h"
#include "StatementSequenceNode.h"
#include "TermNode.h"
#include "TypeDeclarationNode.h"
#include "VarDeclarationNode.h"
#include "WhileStatementNode.h"
// TODO remove again; Instead move all those includes into sensible files
